### ISSUE TITLE
Sample data for EmployeeProfile without connected SF

### ISSUE THREAD

**Issue by ghost** [SAP-samples/successfactors-extension-calculate-employee-seniority#17]
Hi @jmsrpp,

we recently noticed, that we didn't have the EmployeeProfile entity in our version of the hr seniority app.
We retraced our steps and noticed, that this was on another branch, so we reworked a little.

The [mission on the discovery center](https://discovery-center.cloud.sap/protected/index.html#/mymissiondetail/40664/card/9207976/?tab=projectboard) states:

_`As a final step before you access the entities, add a sample exception record so EmployeeProfile returns some data. You can use the POST request in [request.http](https://discovery-center.cloud.sap/sfsf-mobile-appgyver/srv/request.http#L7) in conjunction with cds watch from SAP Business Application Studio`_

Can you elaborate please what exactly needs to be done?
I don't see any POST for EmployeeProfile (which makes sense, since it's only a view).

We managed to create some employee data though (which we can also get using the Employee entity) using the POSTs of the request.http file:

```json
{
	"@odata.context": "$metadata#Employee",
	"value": [{
		"createdAt": "2022-09-30T07:32:54.485Z",
		"createdBy": "privileged",
		"modifiedAt": "2022-09-30T07:32:54.485Z",
		"modifiedBy": "privileged",
		"ID": "1ef973e5-8c26-4662-bded-832b3ef003a9",
		"userId": "42357",
		"hireDate": "2021-04-01T00:00:00.000Z",
		"originalStartDate": "2021-04-02T00:00:00.000Z",
		"status": "HIRENEW",
		"seniority": null,
		"terminationDate": null
	}, {
		"createdAt": "2022-09-27T08:52:39.154Z",
		"createdBy": "privileged",
		"modifiedAt": "2022-09-27T08:52:39.154Z",
		"modifiedBy": "privileged",
		"ID": "47ce07f5-64c4-4ee7-98b2-e54267588441",
		"userId": "12377",
		"hireDate": "2021-01-01T00:00:00.000Z",
		"originalStartDate": "2021-02-01T00:00:00.000Z",
		"status": "HIRENEW",
		"seniority": null,
		"terminationDate": null
	}, {
		"createdAt": "2022-09-30T07:32:24.865Z",
		"createdBy": "privileged",
		"modifiedAt": "2022-09-30T07:32:24.865Z",
		"modifiedBy": "privileged",
		"ID": "4db38320-82a3-441c-908c-1c6d060b5fd4",
		"userId": "12357",
		"hireDate": "2021-02-01T00:00:00.000Z",
		"originalStartDate": "2021-03-01T00:00:00.000Z",
		"status": "HIRENEW",
		"seniority": null,
		"terminationDate": null
	}, {
		"createdAt": "2022-09-30T07:34:02.282Z",
		"createdBy": "privileged",
		"modifiedAt": "2022-09-30T07:34:02.282Z",
		"modifiedBy": "privileged",
		"ID": "63e68e61-b392-43dd-bd6d-d9164ca23b49",
		"userId": "86757",
		"hireDate": "2021-08-08T00:00:00.000Z",
		"originalStartDate": "2021-09-02T00:00:00.000Z",
		"status": "HIRENEW",
		"seniority": null,
		"terminationDate": null
	}, {
		"createdAt": "2022-09-30T07:33:19.486Z",
		"createdBy": "privileged",
		"modifiedAt": "2022-09-30T07:33:19.486Z",
		"modifiedBy": "privileged",
		"ID": "8725b965-e588-4f23-ad09-36cef2d0cc7e",
		"userId": "46757",
		"hireDate": "2021-04-08T00:00:00.000Z",
		"originalStartDate": "2021-07-02T00:00:00.000Z",
		"status": "HIRENEW",
		"seniority": null,
		"terminationDate": null
	}, {
		"createdAt": "2022-09-30T07:34:16.219Z",
		"createdBy": "privileged",
		"modifiedAt": "2022-09-30T07:34:16.219Z",
		"modifiedBy": "privileged",
		"ID": "90ceaa33-cd1b-4aeb-9279-d20c92ba4666",
		"userId": "89857",
		"hireDate": "2021-09-08T00:00:00.000Z",
		"originalStartDate": "2021-12-02T00:00:00.000Z",
		"status": "HIRENEW",
		"seniority": null,
		"terminationDate": null
	}, {
		"createdAt": "2022-09-30T07:34:30.869Z",
		"createdBy": "privileged",
		"modifiedAt": "2022-09-30T07:34:30.869Z",
		"modifiedBy": "privileged",
		"ID": "9d557c39-81a2-4f4e-aa68-d592f6b37bb1",
		"userId": "89887",
		"hireDate": "2021-10-06T00:00:00.000Z",
		"originalStartDate": "2021-12-06T00:00:00.000Z",
		"status": "HIRENEW",
		"seniority": null,
		"terminationDate": null
	}]
}
```

But when we try to get data from the EmployeeProfile entity, the result is empty:

```json
{"@odata.context":"$metadata#EmployeeProfile","value":[{}]}
```

Thanks for any hints.

Regards
Jan

**Comment by jmsrpp** [comment]
Hi @muellerj93 - This is a really great question, thanks for logging it in the repo. I have updated the README with the easy fixes:

* Update to indicate the POST is to Employee entity and not the EmployeeProfile view and that you need to use a REH status to create the exception.
* Point to the correct line in request.http to create a record with status = 'EXCEPTION' which is needed to return data to the UI.

In the short-term, you can fix this by commenting the [service logic](https://github.com/SAP-samples/successfactors-extension-calculate-employee-seniority/blob/sfsf-mobile-appgyver/srv/emp-service.js#L53-L91) that implements the join with the remote system. Keep in mind you would also need to modify the view in the [corresponding CDS](https://github.com/SAP-samples/successfactors-extension-calculate-employee-seniority/blob/sfsf-mobile-appgyver/srv/emp-service.cds#L30-L48) or return null values for the currently mixed-in fields.

Now, I am assigning this issue to @hterminasyan because he and I just discussed enhancing the mission with a mock service for folks that don't have an SAP SuccessFactors tenant to test with. @hterminasyan please feel free to reassign or open a new issue to highlight the change once we start work.

**Comment by ghost** [comment]
Hi @jmsrpp,

thanks, we'll try with your proposed short-term fixes :)

**Comment by hterminasyan** [comment]
the mock service was implemented, see https://github.com/SAP-samples/successfactors-extension-calculate-employee-seniority
